[project]
name = "api-activiy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CallingBoar", email = "bmtzm@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "flask-restful>=0.3.10",
    "pytest>=9.1.1",
    "requests>=2.34.2",
]

[project.scripts]
api-activiy = "api_activiy:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
